version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  
  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm install
      
  build:
    commands:
      - echo "Building application"
      - npm run build
      
  post_build:
    commands:
      - echo "Preparing deployment package"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/**/*
  discard-paths: no
