version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
  
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan -out=tfplan
      - terraform show -json tfplan > tfplan.json

  post_build:
    commands:
      - aws s3 cp tfplan s3://${ARTIFACT_BUCKET}/tfplan
      - aws s3 cp tfplan.json s3://${ARTIFACT_BUCKET}/tfplan.json

artifacts:
  files:
    - tfplan
    - tfplan.json
    - '**/*'
